### ISSUE TITLE
Unable to compile buildpack for newest Heroku stack

### ISSUE THREAD

**Issue by harrylewis** [benmurden/nginx-pagespeed-buildpack#2]
Hi @benmurden 👋 

I just wanted to start off by thanking you for building/maintaining this buildpack. It has been invaluable to my team in order to support Google PageSpeed!

We are currently embarking on a Heroku stack upgrade to Heroku-20. I am trying to re-compile the source on that stack using `scripts/build_nginx.sh`. I naively tried to download this repository and push it to a newly created Heroku application, hoping that the `Procfile` directive would make the compiled source immediately downloadable.

I could not get past the build phase, since the repository has no file that gives Heroku insight into which language buildpack to use.

```
[buildpack-nginx-pagespeed-ssl]$ git push heroku master
Enumerating objects: 756, done.
Counting objects: 100% (756/756), done.
Delta compression using up to 4 threads
Compressing objects: 100% (384/384), done.
Writing objects: 100% (756/756), 54.92 MiB | 2.87 MiB/s, done.
Total 756 (delta 321), reused 756 (delta 321)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to testing-nginx.
remote:
To https://git.heroku.com/testing-nginx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/testing-nginx.git'
```

Can you provide some insight into how I might go about re-compiling this?

**Comment by benmurden** [comment]
Hi @harrylewis

Thanks for taking the time to try and resolve this! When recently trying to rebuild the binaries I have used the Docker image from https://registry.hub.docker.com/r/heroku/heroku, which will allow for easier debugging of the process.

Let me know if you have more luck using that approach. I will take a look at this myself when I have a moment.

**Comment by benmurden** [comment]
@harrylewis I just updated the buildpack with the latest Nginx / Pagespeed built on the `heroku/heroku:20-build` Docker image.

Could you give it a try and see if it works for you?

**Comment by benmurden** [comment]
@harrylewis I am now using this build on Heroku-20 dynos and haven't noticed any issues. I'm going to close this now, but please reopen if you have trouble.
